In [43]:
c(2,3,5,7)+c(-2,-3,-5,8)

[1]  0  0  0 15

In [44]:
c(2,3,5,7) + c(8,9)

[1] 10 12 13 16

In [45]:
c(2,3,5,7) + c(8,9,10)

Warning message in c(2, 3, 5, 7) + c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 10 12 15 15

In [46]:
c(2,3,5,7) - c(-2,-3,-5,8)

[1]  4  6 10 -1

In [47]:
c(12,13,15,17) - c(8,9)

[1] 4 4 7 8

In [48]:
c(12,13,15,17) - c(8,9,10)

Warning message in c(12, 13, 15, 17) - c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 4 4 5 9

In [49]:
c(2,3,5,7)*c(-2,-3,-5,8)

[1]  -4  -9 -25  56

In [50]:
c(2,3,5,7) * c(8,9)

[1] 16 27 40 63

In [51]:
c(2,3,5,7) * c(8,9,10)

Warning message in c(2, 3, 5, 7) * c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 16 27 50 56

In [52]:
c(24,20,8,26) / c(3,4,2,8)

[1] 8.00 5.00 4.00 3.25

In [53]:
c(24,20,8,26) / c(4,2)

[1]  6 10  2 13

In [54]:
c(24,20,8,26) / c(4,2,8)

Warning message in c(24, 20, 8, 26)/c(4, 2, 8):
“longer object length is not a multiple of shorter object length”

[1]  6.0 10.0  1.0  6.5

In [55]:
x <- 20
x

[1] 20

In [56]:
x=20
x

[1] 20

In [57]:
y=x*2
y

[1] 40

In [58]:
z=x+y
z

[1] 60

In [59]:
x=20
x

[1] 20

In [60]:
x="apple"
x

[1] "apple"

In [61]:
x=20
is.numeric(x)

[1] TRUE

In [62]:
is.character(x)

[1] FALSE

In [63]:
y="apple"
is.character(y)

[1] TRUE

In [64]:
is.numeric(y)

[1] FALSE

In [65]:
x=20
is.numeric(x)

[1] TRUE

In [66]:
y=as.character(x)
is.numeric(y)

[1] FALSE

In [67]:
is.character(y)

[1] TRUE

In [68]:
y

[1] "20"

In [69]:
y="apple"
is.numeric(y)

[1] FALSE

In [70]:
is.character(y)

[1] TRUE

In [71]:
z=as.numeric(y)

Warning message:
“NAs introduced by coercion”

In [72]:
is.numeric(z)

[1] TRUE

In [73]:
is.character(z)

[1] FALSE

In [74]:
z

[1] NA

In [75]:
x <- 20
x

[1] 20

In [76]:
X <- 30
X

[1] 30

In [77]:
y=c(1,2,3,4,5)

In [78]:
x=6
x
mode(x)

[1] 6

[1] "numeric"

In [79]:
y="apple"
y
mode(y)

[1] "apple"

[1] "character"

In [80]:
x=6
storage.mode(x)

[1] "double"

In [81]:
x=TRUE
storage.mode(x)

[1] "logical"

In [82]:
x="apple"
storage.mode(x)

[1] "character"

In [83]:
3/0
5+Inf
x=5+Inf
is.finite(x)

is.infinite(x)

[1] Inf

[1] Inf

[1] FALSE

[1] TRUE

In [84]:
2+3
2*3
2-3
3/2
2*3-4+5/6

[1] 5

[1] 6

[1] -1

[1] 1.5

[1] 2.833333

In [85]:
(2+3)*5+5-10
(((2+3)*5+5)-10)/2

[1] 20

[1] 10

In [86]:
c(2,3,5,7)+10
c(12,13,15,17)-10
c(2,3,5,7)*10
c(12,13,15,17)/10

[1] 12 13 15 17

[1] 2 3 5 7

[1] 20 30 50 70

[1] 1.2 1.3 1.5 1.7

In [87]:
2^3
2**3

[1] 8

[1] 8

In [88]:
2^0.5
2**0.5
2^-0.5

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [89]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [90]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [91]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [92]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [93]:
2%/%2
5%/%2
7%/%3

[1] 1

[1] 2

[1] 2

In [94]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [95]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [96]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [97]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

In [98]:
max(1.2,3.4,-7.8)
max(c(1.2,3.4,-7.8))

[1] 3.4

[1] 3.4

In [99]:
min(1.2,3.4,-7.8)
min(c(1.2,3.4,-7.8))

[1] -7.8

[1] -7.8

In [100]:
mean(2,3,4)
mean(c(2,3,4))

[1] 2

[1] 3

In [101]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

In [102]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

In [103]:
sum(c(2,3,5,7))
prod(c(2,3,5,7))

[1] 17

[1] 210

In [104]:
round(1.23)
round(1.83)

[1] 1

[1] 2

In [105]:
log(10)
log(exp(1))
log(c(10,100,1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

In [106]:
log10(10)
log10(100)
log10(c(10,100,1000))

[1] 1

[1] 2

[1] 1 2 3

In [107]:
x1=c(1,2,3,4)
x1

x2=x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [108]:
c(1,2,3,4)+sum(c(1,2,3,4))*prod(c(1,2))

abs(c(1,2,3,4)-sum(c(1,2,3,4))*prod(c(1,2)))

[1] 21 22 23 24

[1] 19 18 17 16

In [109]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [110]:
x[3,2]

[1] 7

In [111]:
x=matrix(nrow=4,ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [112]:
y=matrix

In [113]:
dim(x)

[1] 4 2

In [114]:
nrow(x)

[1] 4

In [115]:
ncol(x)

[1] 2

In [116]:
mode(x)

[1] "numeric"

In [117]:
attributes(x)

$dim
[1] 4 2

In [118]:
help("matrix")

In [119]:
x=matrix( nrow=4,ncol=3,data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [120]:
rownames(x)
colnames(x)

NULL

NULL

In [121]:
rownames(x)=c("r1","r2","r3","r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [122]:
colnames(x)=c("c1","c2","c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [123]:
x=matrix(nrow=4,ncol=2,data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [124]:
d=diag(1,nrow=3,ncol=3)

In [125]:
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [127]:
d=diag(5,nrow=3,ncol=3)

In [128]:
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [129]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [130]:
xt=t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [132]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [134]:
rowSums(x)
colSums(x)

[1]  6  8 10 12

[1] 10 26

In [135]:
rowMeans(x)
colMeans(x)

[1] 3 4 5 6

[1] 2.5 6.5

In [136]:
x=matrix(nrow=5,ncol=3,byrow=T,data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [137]:
x[3,]

[1] 7 8 9

In [138]:
x[,2]

[1]  2  5  8 11 14

In [139]:
x[4:5,2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [140]:
x[c(1,4),c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [141]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [142]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [143]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [144]:
x-5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [145]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [146]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [147]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [148]:
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [149]:
x+y
x-y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [150]:
 x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [151]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [152]:
x+4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [153]:
4*x-x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [154]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)
y=matrix(nrow=2,ncol=4,data=11:18,byrow=T)
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [156]:
x%*%y
y%*%x

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [157]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [158]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [159]:
t(x)%*%x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [160]:
x%*%t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [161]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [162]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

In [164]:
x
y
rbind(x,y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [165]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [166]:
y = matrix( nrow = 2, ncol = 2, byrow = T,
data = c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [167]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [172]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [173]:
x=8
(x<10)||(x<2)

[1] TRUE

In [174]:
x=18
(x<10)||(x<2)

[1] FALSE

In [177]:
x = c(8,18)

In [179]:
x=5
(x<10)&&(x>2)

[1] TRUE

In [180]:
x=15
(x<10)&&(x>2)

[1] FALSE

In [182]:
x=c(8,18)
(x<10)&(x>2)

[1]  TRUE FALSE

In [183]:
x=1:6

In [184]:
x

[1] 1 2 3 4 5 6

In [185]:
(x>2)&(x<5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [186]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [187]:
 x = 1:6

In [188]:
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [189]:
[(x > 2) | (x < 5)]

ERROR: Error in parse(text = input): <text>:1:1: unexpected '['
1: [
    ^

In [191]:
 x = 1:6

In [193]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

In [194]:
x = TRUE
y = FALSE
x & y

[1] FALSE

In [195]:
x|y

[1] TRUE

In [196]:
!x

[1] FALSE

In [197]:
x = 5
7
Logical1 = (x > 2)
Logical1

is.logical(Logical1)

Logical2 = (x < 10)
 Logical2

is.logical(Logical2)

Logical3 = (x != 5)
Logical3

is.logical(Logical3)

[1] 7

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

In [198]:
x = 5
Logical4 = (2*x > 11)
Logical4

is.logical(Logical4)

Logical5 = (3*x <20)
Logical5

is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

In [199]:
8 > 7
7 < 5
7 > 7
7 >= 7

8 < 8
8 <= 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

In [201]:
8 != 9
 9 != 9
 7 == 7
 7 == 8
 x = TRUE
!x

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

In [202]:
 x = c(1, 2, 3)
 y = c(4, 5, 6)

In [203]:
x>y

[1] FALSE FALSE FALSE

In [204]:
x<y

[1] TRUE TRUE TRUE

In [205]:
x!=y

[1] TRUE TRUE TRUE

In [206]:
x==y

[1] FALSE FALSE FALSE

In [208]:
isTRUE(8 < 6)

[1] FALSE

In [209]:
isTRUE(8>6)

[1] TRUE

In [210]:
isFALSE(5 < 8)

[1] FALSE

In [211]:
isFALSE(5 > 8)

[1] TRUE